name: GitHub Action Events

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Optional: For testing merge events as well
  pull_request_target:
    branches:
      - main

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger Webhook on Push, PR, Merge
        run: |
          curl -X POST http://localhost:5000/webhook -H "Content-Type: application/json" -d '{"action":"push", "sender": {"login": "username"}, "pull_request": {"head": {"ref": "branch1"}, "base": {"ref": "branch2"}}}'
