name: GitHub Action Events

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger Webhook
        run: |
          curl -X POST https://ff2b-103-180-2-66.ngrok-free.app/webhook \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: ${{ github.event_name }}" \
            -d '${{ toJSON(github.event) }}'